<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit3eeba524e231be56b023b35983be855b
{
    public static $prefixLengthsPsr4 = array (
        'T' => 
        array (
            'Twilio\\' => 7,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Twilio\\' => 
        array (
            0 => __DIR__ . '/..' . '/twilio/sdk/src/Twilio',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit3eeba524e231be56b023b35983be855b::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit3eeba524e231be56b023b35983be855b::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInit3eeba524e231be56b023b35983be855b::$classMap;

        }, null, ClassLoader::class);
    }
}
